apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.name}}
    env: {{.Values.env}}
    app.kubernetes.io/name: {{.Values.name}}
spec:
  selector:
    app: {{.Values.name}}
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{.Values.nodePort}}